=== Alex-Poiana/ahmetAlex.poiana.XML-DOM/file_xml/file_dtd_xsd/tabellaSharkDive.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT tabellaSharkDive (service*)>
<!ELEMENT service (nomeServizio, data, costo)>
<!ATTLIST service
            serviceId ID #REQUIRED>
      
  <!ELEMENT nomeServizio (#PCDATA)>
   <!ELEMENT data (#PCDATA)>
  <!ELEMENT costo (#PCDATA)>

=== Alex-Poiana/ahmetAlex.poiana.XML-DOM/file_xml/tabellaSharkDiveCopia.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE tabellaSharkDive SYSTEM "file_dtd_xsd/tabellaSharkDive.dtd">
 
<!-- <tabellaSharkDive xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="file_dtd_xsd/tabellaSharkDive.xsd">-->
<tabellaSharkDive>
  <service serviceId="sh1">
    <nomeServizio>Shark Diving</nomeServizio>
    <data>2024-07-25</data>
    <costo>89</costo>
  </service>
  
    <service serviceId="sh2">
    <nomeServizio>Shark Diving</nomeServizio>
    <data>2024-07-28</data>
    <costo>89</costo>
  </service>
  
  </tabellaSharkDive>
