=== Alex-Poiana/ahmetAlex.poiana.XML-DOM/file_xml/file_dtd_xsd/tabellaUser.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tabellaUser (user+)>
<!ELEMENT user (username, password, genere, nazione,  tipologia, sommeSpese, ban, serviziAcquistati?)>
<!ATTLIST user
                userId ID #REQUIRED>
                
  <!ELEMENT username (#PCDATA)>
  <!ELEMENT password (#PCDATA)>
  <!ELEMENT genere (#PCDATA)>
  <!ELEMENT nazione (#PCDATA)>
  <!ELEMENT tipologia (#PCDATA)>
  <!ELEMENT sommeSpese (#PCDATA)>
  <!ELEMENT ban (#PCDATA)>
  <!ELEMENT serviziAcquistati (servizio+)>
  <!ELEMENT servizio EMPTY>
  <!ATTLIST servizio
                    serviceId ID #REQUIRED
                    tipoServizio (whaleWatching | dolphinSwimming | sharkDiving)  #REQUIRED
                    quanteCopie CDATA #REQUIRED>

=== Alex-Poiana/ahmetAlex.poiana.XML-DOM/file_xml/tabellaUser.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE tabellaUser SYSTEM "file_dtd_xsd/tabellaUser.dtd">
 
 <!--<tabellaUser  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="file_dtd_xsd/tabellaUser.xsd">-->
<tabellaUser>
  <user userId="user1">
    <username>Master</username>
    <password>dragon</password>
    <genere>maschio</genere>
    <nazione>Italia</nazione>
    <tipologia>admin</tipologia>
    <sommeSpese>0</sommeSpese>
    <ban>nonAttivo</ban>
  </user>
  
   <user userId="user2">
    <username>Dario</username>
    <password>atomico</password>
    <genere>maschio</genere>
    <nazione>Italia</nazione>
    <tipologia>gestore</tipologia>
    <sommeSpese>0</sommeSpese>
    <ban>nonAttivo</ban>
  </user>
  
   <user userId="user3">
    <username>Thomas</username>
    <password>naku</password>
    <genere>maschio</genere>
    <nazione>Italia</nazione>
    <tipologia>utente</tipologia>
    <sommeSpese>0</sommeSpese>
    <ban>nonAttivo</ban>
  </user>
  
   <user userId="user4">
    <username>Enzo</username>
    <password>vinzz</password>
    <genere>maschio</genere>
    <nazione>Italia</nazione>
    <tipologia>utente</tipologia>
    <sommeSpese>0</sommeSpese>
    <ban>nonAttivo</ban>
  </user>
  
   <user userId="user5">
    <username>Ignazio</username>
    <password>pignuis</password>
    <genere>maschio</genere>
    <nazione>Italia</nazione>
    <tipologia>utente</tipologia>
    <sommeSpese>0</sommeSpese>
    <ban>attivo</ban>
  </user>
  
  </tabellaUser>

=== Alex-Poiana/ahmetAlex.poiana.XML-DOM/file_xml/tabellaUserCopia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tabellaUser SYSTEM "file_dtd_xsd/tabellaUser.dtd">
<!--<tabellaUser  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xsi:noNamespaceSchemaLocation="file_dtd_xsd/tabellaUser.xsd">-->
<tabellaUser><user userId="user1"><username>Master</username><password>dragon</password><genere>maschio</genere><nazione>Italia</nazione><tipologia>admin</tipologia><sommeSpese>0</sommeSpese><ban>nonAttivo</ban></user><user userId="user2"><username>Dario</username><password>atomico</password><genere>maschio</genere><nazione>Italia</nazione><tipologia>gestore</tipologia><sommeSpese>0</sommeSpese><ban>nonAttivo</ban></user><user userId="user3"><username>Thomas</username><password>naku</password><genere>maschio</genere><nazione>Italia</nazione><tipologia>utente</tipologia><sommeSpese>1061</sommeSpese><ban>nonAttivo</ban><serviziAcquistati><servizio serviceId="ww1" tipoServizio="whaleWatching" quanteCopie="3"/><servizio serviceId="ds2" tipoServizio="dolphinSwimming" quanteCopie="3"/><servizio serviceId="sh2" tipoServizio="sharkDiving" quanteCopie="2"/><servizio serviceId="sh1" tipoServizio="sharkDiving" quanteCopie="1"/><servizio serviceId="ds1" tipoServizio="dolphinSwimming" quanteCopie="1"/><servizio serviceId="ww2" tipoServizio="whaleWatching" quanteCopie="1"/></serviziAcquistati></user><user userId="user4"><username>Enzo</username><password>vinzz</password><genere>maschio</genere><nazione>Italia</nazione><tipologia>utente</tipologia><sommeSpese>135</sommeSpese><ban>nonAttivo</ban><serviziAcquistati><servizio serviceId="ww3" tipoServizio="whaleWatching" quanteCopie="1"/><servizio serviceId="ds3" tipoServizio="dolphinSwimming" quanteCopie="1"/><servizio serviceId="sh3" tipoServizio="sharkDiving" quanteCopie="1"/></serviziAcquistati></user><user userId="user5"><username>Ignazio</username><password>pignuis</password><genere>maschio</genere><nazione>Italia</nazione><tipologia>utente</tipologia><sommeSpese>0</sommeSpese><ban>attivo</ban></user><user userId="user6"><username>Flavio</username><password>domino</password><genere>maschio</genere><nazione>Italia</nazione><tipologia>utente</tipologia><sommeSpese>0</sommeSpese><ban>nonAttivo</ban></user><user userId="user7"><username>Antonio</username><password>trxanto</password><genere>maschio</genere><nazione>Italia</nazione><tipologia>utente</tipologia><sommeSpese>0</sommeSpese><ban>nonAttivo</ban></user></tabellaUser>
